#!/usr/bin/env python3
import requests
import yaml
import argparse
import json
import os
import webbrowser
import urllib
import base64
import time
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler

access_token = ""
server = None

def readConfig(cfile):
    with open(cfile, mode='r') as f:
        cdict = yaml.safe_load(f)
    return cdict

def getEthernetInterfaces(smd_url, access_token=""):
    headers = {}
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    r = requests.get(smd_url+'/Inventory/EthernetInterfaces', headers=headers)
    data = r.json()
    return data

def deleteEthernetInterface(xname, smd_url, access_token=""):
    headers = {}
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    smd_data = getEthernetInterfaces(smd_url)
    for s in smd_data:
        if s['ComponentID'] == xname:
            print("Match found "+ xname)
            smd_id = s['ID']
            r = requests.delete(smd_url+'/Inventory/EthernetInterfaces/'+smd_id, headers=headers)

def ethernetInterfacePayload(smd):
    sdata = {
            "Description": "Interface for " + smd['name'],
            "MACAddress": smd['mac'],
            "IPAddresses": [
                {
                    "IPAddress": smd['ipaddr'],
                    "Network": "NMN"
                    }
                ],
            "ComponentID": smd['xname']
            }
    return sdata

def nodeComponentPayload(smd):
    sdata = {
            "Components": [
                {
                    "ID": smd['xname'],
                    "State": "Ready",
                    "Enabled": True,
                    "Role": "Compute",
                    "Arch": "X86",
                }
            ],
            "Force": False
            }
    return sdata

def getBSS(bss_url):
    r = requests.get(bss_url)
    data = r.json()
    return data

def getSMDComponents(smd_url, xname, access_token=""):
    headers = {}
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    if not xname:
        r = requests.get(smd_url+'/State/Components', headers=headers)
        data = r.json()
    else:
        r = requests.get(smd_url+'/State/Components/'+xname, headers=headers)
        data = r.json()
    return data

def getSMDInterfaces(smd_url, xname, access_token=""):
    headers = {}
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    r = requests.get(smd_url+'/Inventory/EthernetInterfaces', headers=headers)
    data = r.json()
    if not xname:
        return data
    else:
        for s in data:
            if s['ComponentID'] == xname:
                return s

class AccessTokenHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.receive_token()

    def receive_token(self):
        # length = int(self.headers.get('content-length'))
        # field_data = self.rfile.read(length)
        # fields = urllib.parse.parse_qs(str(field_data,"UTF-8"))
        if self.headers.get("access_token"):
            global access_token
            global server
            access_token = self.headers.get('access_token')
            with open(".ochami-token", "w+") as f:
                f.write(access_token)
            print(f"token received: {access_token}")
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            threading.Thread(target=server.shutdown, daemon=True).start()

def login(url: str, host: str, port: int) -> str:
    global access_token
    global server
    # open browser and wait for access code if target is set
    if host:
        url += f"?target={urllib.parse.quote_plus(f'http://{host}:{port}')}"
    is_open = webbrowser.open(url)
    if is_open:
        print(f"waiting to receive an access token...")
        if host:
            try:
                server = HTTPServer((host, port), AccessTokenHandler)
                while not access_token:
                    server.serve_forever()
            except KeyboardInterrupt:
                print("shutting down without receiving token")
                server.shutdown()

def is_access_token_valid(token: str) -> bool:
    # NOTE: doing validation manually even though PyJwt can do this as well
    # no token is automatically invalid
    if not token:
        print("no token found")
        return False
    
    # base64 decode the token into its 3 segments
    segments = token.split(".", 3)
    decoded_segments = []
    for segment in segments:
        padded = segment + "="*divmod(len(segment),4)[1]
        decoded_segments.append(base64.urlsafe_b64decode(padded))
    
    # check payload for expiration date (token is valid if it doesn't exist)
    if len(decoded_segments) >= 2:
        payload = json.loads(decoded_segments[1])
        expires_at = payload["exp"]
        if expires_at:
            current_time = time.time()
            return current_time < expires_at
    else:
        print("could not validate token")
        return False

def setArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument("--access-token", dest="access_token", default="", type=str)
    parser.add_argument("--access-token-file", dest="access_token_file", default=".ochami-token", type=str)
    subparser = parser.add_subparsers(dest='command')

    smd = subparser.add_parser('smd')
    smd.add_argument('--config', type=str)
    smd.add_argument('--url',type=str)
    smd.add_argument('--add-node', dest='add_node', action="store_true", default=False)
    smd.add_argument('--delete-node', dest='delete_node', action="store_true", default=False)
    smd.add_argument('--add-interface', dest='add_interface', action="store_true", default=False)
    smd.add_argument('--delete-interface', dest='delete_interface', action="store_true", default=False)
    smd.add_argument('--get-components', dest='get_components', action="store_true", default=False)
    smd.add_argument('--get-interfaces', dest='get_interfaces', action="store_true", default=False)
    smd.add_argument('--name',type=str)
    smd.add_argument('--xname',type=str)
    smd.add_argument('--mac',type=str)
    smd.add_argument('--ipaddr',type=str)
    bss = subparser.add_parser('bss')
    bss.add_argument('--config',type=str)
    bss.add_argument('--url', type=str)
    bss.add_argument('--add-bootparams', dest='add_bootparams', action="store_true", default=False)
    bss.add_argument('--update-bootparams', dest='update_bootparams', action="store_true", default=False)
    login = subparser.add_parser('login')
    login.add_argument("--url", type=str, default="http://127.0.0.1:3333/login", help="set the login URL")
    login.add_argument("--target-host", dest='host', type=str, default="127.0.0.1", help="set the target host receive access token")
    login.add_argument("--target-port", dest='port', type=int, default=5000, help="set the target port receive access token")
    args = parser.parse_args()
    return args

def main():
    global access_token
    args = setArgs()
    headers = {}
    if os.getenv("OCHAMI_ACCESS_TOKEN"):
        access_token = os.getenv(f"{os.getenv('OCHAMI_ACCESS_TOKEN')}")
        headers = {"Authorization": f"Bearer {os.getenv('OCHAMI_ACCESS_TOKEN')}"}
    if args.access_token:
        access_token = args.access_token
        if access_token:
            headers = {"Authorization": f"Bearer {args.access_token}"}
    elif args.access_token_file:
        if os.path.exists(args.access_token_file):
            with open(args.access_token_file, "r") as f:
                access_token = f.read()
                if access_token:
                    headers = {"Authorization": f"Bearer {access_token}"}

    if args.command == "smd":
        smd_url = args.url
        if args.config:
            config = args.config
            cdict = readConfig(config)
            for c in cdict['nodes']:
                nc = nodeComponentPayload(c)
                r = requests.post(smd_url+'/State/Components', json = nc, headers=headers)
                print(r.reason)
                ei = ethernetInterfacePayload(c)
                r = requests.post(smd_url+'/Inventory/EthernetInterfaces', json = ei, headers=headers)
                print(r.reason)
        elif args.add_node:
            nc = nodeComponentPayload({'name': args.name,'xname': args.xname,'mac': args.mac, 'ipaddr': args.ipaddr})
            r = requests.post(smd_url+'/State/Components', json = nc, headers=headers)
            print(r.reason)
        elif args.delete_node:
            r = requests.delete(smd_url+'/State/Components/'+args.xname, headers=headers)
        elif args.add_interface:
            ei = ethernetInterfacePayload({'name': args.name,'xname': args.xname,'mac': args.mac, 'ipaddr': args.ipaddr})
            r = requests.post(smd_url+'/Inventory/EthernetInterfaces', json = ei, headers=headers)
            print(r.reason)
        elif args.delete_interface:
            deleteEthernetInterface(args.xname, smd_url)
        elif args.get_components:
            sc = getSMDComponents(smd_url, args.xname, access_token)
            json_formatted_str = json.dumps(sc, indent=2)
            print(json_formatted_str)
        elif args.get_interfaces:
            si = getSMDInterfaces(smd_url, args.xname)
            json_formatted_str = json.dumps(si, indent=2)
            print(json_formatted_str)


    elif args.command == "bss":
        config = args.config
        bss_url = args.url
        cdict = readConfig(config)
        if args.add_bootparams:
            r = requests.post(bss_url+'/bootparameters', json = cdict, headers=headers)
            print(r.reason)
        elif args.update_bootparams:
            r = requests.delete(bss_url+'/bootparameters', json = cdict, headers=headers)
            print(r.reason)
            r = requests.post(bss_url+'/bootparameters', json = cdict, headers=headers)
            print(r.reason)
    
    elif args.command == "login":
        url = args.url
        host = args.host
        port = args.port
        # todo: only try to log in if we have an invalid token
        if not is_access_token_valid(access_token):
            access_token = ""
            login(url, host, port)
        else:
            print("found a valid token")


if __name__ == "__main__":
    main()

# example usage: ./ochami-cli smd --config config.yml --url http://127.0.0.1:27779/hsm/v2
